apiVersion: infra.k8/v1alpha1
kind: XDatabase
metadata:
  name: orders-prod
spec:
  name: orders-prod
  engine: yugabytedb
  version: "2.21"
  size: large
  storageGB: 500
  tier: production
  cluster: hub
  owner: orders-team
