apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-demo
  namespace: argocd
spec:
  project: demo
  source:
    repoURL: https://github.com/Cliftonz/akuity-deployment-examples
    targetRevision: HEAD
    path: demo/charts/guestbook
    helm:
      releaseName: guestbook
  destination:
    name: demo
    namespace: guestbook-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
