apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
    # Required for the Traefik Gateway to allow HTTPRoutes from this ns.
    routes-from: business
