apiVersion: infra.k8/v1alpha1
kind: XResourceQuota
metadata:
  name: traefik-quota
spec:
  name: traefik-quota
  namespace: traefik
  tier: dev
  cluster: demo
  owner: platform-team
  hard:
    requests.cpu: 250m
    requests.memory: 256Mi
    limits.cpu: "1"
    limits.memory: 512Mi
    pods: "5"
