apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/Cliftonz/akuity-deployment-examples
  destinations:
    - namespace: guestbook-demo
      server: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: gateway.networking.k8s.io
      kind: "*"
