apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-prod

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: guestbook
    patch: |-
      - op: replace
        path: /metadata/name
        value: guestbook-prod
  - target:
      kind: Deployment
      name: guestbook
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m

images:
  - name: ghcr.io/<user>/guestbook
    newTag: v0.0.1

labels:
  - pairs:
      env: prod
    includeSelectors: false
